### ISSUE TITLE
[Specifications] Transformation artifacts

### ISSUE THREAD

**Issue by tchataigner** [polyphene/holium-rs-sdk#3]
When compiling rust code to generate the wasm bytecode we should generates some artifacts to retrieve metadata from the base code. The format for the metadata should be human readable and editable as some documentation might have to be completed for example. 

Here is a first proposal to open the discussion:

# Artifacts generation

Deux fichiers : bytecode & metadata

## Metadata file

Format: TOML

#### Metadata

Contains metadata to associate to a transformation bytecode

- Name: String
- Documentation: String
- Version: String

#### Structure

Structure represents custom types defined by the transformation developer

- Name: String
- Documentation: String
- Fields: Fields

#### Transformation

Transformation represents a function in the library

- Name: String
- Documentation: String
- Inputs: Fields
- Outputs: Fields

#### Fields

- Key: String
- Type: Enum(Bool, Integer, Float, Bytes, Text, <any_structure>) 

### Sample

```toml
[metadata]
version = "1.0.0"
name = "Library name"
documentation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis eros quis ante facilisis ultrices id at neque. Praesent justo metus, volutpat sit amet nisi vel, molestie sagittis quam. Vivamus ante neque, sollicitudin vel viverra quis, ultricies ac ante. Donec et gravida purus. Vestibulum pharetra leo vel scelerisque maximus. Vivamus purus nisl, mollis in ante at, egestas euismod erat. Pellentesque ullamcorper bibendum orci a posuere"

[[transformations]]
name = "main"
documentation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis eros quis ante facilisis ultrices id at neque. Praesent justo metus, volutpat sit amet nisi vel, molestie sagittis quam. Vivamus ante neque, sollicitudin vel viverra quis, ultricies ac ante. Donec et gravida purus. Vestibulum pharetra leo vel scelerisque maximus. Vivamus purus nisl, mollis in ante at, egestas euismod erat. Pellentesque ullamcorper bibendum orci a posuere"
  
  [[transformations.inputs]]
  key = "key0"
  type = "Null"
  
  [[transformations.output]]
  key = "key1"
  type = "Structure"
  
[[structures]]
name = "Strucutre"
documentation = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis eros quis ante facilisis ultrices id at neque. Praesent justo metus, volutpat sit amet nisi vel, molestie sagittis quam. Vivamus ante neque, sollicitudin vel viverra quis, ultricies ac ante. Donec et gravida purus. Vestibulum pharetra leo vel scelerisque maximus. Vivamus purus nisl, mollis in ante at, egestas euismod erat. Pellentesque ullamcorper bibendum orci a posuere"
  
  [[structures.fields]]
  key = "key0"
  type = "Text"
  
  
```
